#!/usr/bin/perl

# Copyright (c) 2015 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;

use JSON;
my $json = JSON->new->allow_nonref;

my ($line,$cmd,$ret);
while(<stdin>) {
	chomp($line = $_);
	$cmd = "ftp -o - 2>/dev/null http://blockr.io/api/v1/tx/info/".$line;
	$ret = open(TX,$cmd."|");
	if ($ret < 1) {
		die "open returned $ret";
	}
	my $result = "";
	while(<TX>) {
		$result .= $_;
	}
	close(TX);
	printf "%s: %d len result\n",$line,length($result);
	if (length($result) == 0) {
		next;
	}
	my $parsed;
	eval {
		$parsed = $json->decode( $result );
	};
	if ($@) {
		printf "json->decode('%s') Error: %s\n", $result, $@;
		next;
	}
	print $json->pretty->encode( $parsed );
}
