#!/bin/ksh

# Copyright (c) 2014 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

delay=30
cmd="btcctl"
mailaddr=""
minconf="1"
bg=1
onecheck=0
runqueue=0
queuedir=$HOME/var/spool/watchtxq
td=$(mktemp -d /tmp/watchtx.XXXXXXXXXXXXXXX)
trap 'rm -rf $td' 0 1 2 3 13 15



[ -f ~/.watchtx.conf ] && . ~/.watchtx.conf

while [ "$1" ]
do
	case "$1" in
	-t) shift; delay="$1";;
	-c) shift; cmd="$1";;
	-m) shift; mailaddr="$1";;
	-C) shift; minconf="$1";;
	-fg) bg=0;;
	-1) onecheck=1;;
	-rq) runqueue=1;;
	*) break;;
	esac
	shift
done
args="$@"

mkdir -p "$queuedir"

getinfo() {
	local tx="$1"
	$cmd gettransaction $tx > $td/txinfo
}
getconf() {
	local tx="$1"
	getinfo $tx
	awk '/confirmations/{sub(",","");print $2}' $td/txinfo
}
getheight() {
	local tx="$1"
	getinfo $tx
	local bhash=$(awk '/blockhash/{sub(",","");gsub("\"","");print $2}' $td/txinfo)
	$cmd getblock $bhash | awk '/height/{sub(",","");print $2}'
}
showtxinfo() {
	local tx="$1"
	echo "$(date) confirmations=$(getconf $tx) height=$(getheight $tx)"
}

if [ runqueue -eq 1 ]; then
	for f in "$queuedir"/*
	do
		[ -f "$f" ] || continue
		[ -s "$f" ] || continue
		sh "$f"
	done
fi

tx="$1"

if ! [ "$tx" ]; then
	echo "No tx arg, bailing"
	echo
	echo "Usage:"
	echo " watchtx [-t <pollsecs>] [-c <btcctl ...>] [-m a@b.c] [-C <minconf>] <txid>"
	exit 1
fi
if [ bg -eq 1 ]; then
	echo "Queueing txid $tx"
	TMPDIR="$queuedir"
	file=$(mktemp)
	echo "$0 -fg -1 -t $delay -c \"$cmd\" -m $mailaddr -C $minconf $args" > "$file"
	exit 0
fi

lastconf=0
while :
do
	confirmations=$(getconf "$tx")
	if ! [ "$confirmations" ]; then
		echo "Error reading confirmations, bailing"
		exit 1
	fi
	if [ $confirmations -ge $minconf ]; then
		break
	fi
	if [ $confirmations -gt 0 ]; then
		if [ $lastconf -lt $confirmations ]; then
			showtxinfo "$tx"
			lastconf=$confirmations
		fi
	fi
	if [ onecheck -eq 1 ]; then
		exit 0
	fi
	sleep $delay
done > $td/watch.log 2>&1
showtxinfo "$tx"
if [ "$mailaddr" ]; then
	{
		cat $td/txinfo
		echo
		cat $td/watch.log
	} | mail -s "confirmed tx $tx" $mailaddr < $td/txinfo
date
exit 0
